### ISSUE TITLE
Where is the site located at?

### ISSUE THREAD

**Issue by Jme7** [pelletsstarPL/Magixmod#1]
I seem to remember a website for this mod, but I can't find it anymore and I am having trouble adding the mod. Could you give a link to the website? Thanks!

**Comment by pelletsstarPL** [comment]
To install mod:
before you start game you will see popup with name and Awful,Pleasant etc.
So there click use mods.
After that remove *data.js* line
and replace it with link to mod's code:
https://cdn.jsdelivr.net/gh/MagixModLegacy/magix@master/MagixOfficial_b184.js
Yeah you need to paste it.
Then load mods and enjoy

wt., 10 lis 2020 o 05:27 Jme <notifications@github.com> napisał(a):

**Comment by Jme7** [comment]
Ok, thanks!
